language: generic

sudo: required
services:
  -docker

before_install:
  - docker build -t mikhaelcutajar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikhaelcutajar/docker-react npm run test